name = "DistSSHRun"
uuid = "b568025c-2759-4ef1-8b14-17d00e2cd000"
license = "MIT"
version = "0.1.0"
authors = ["Yamamoto, Takanori <takanori.yamamoto.99@gmail.com>", "Ampuku, Honoka <ampk.hono@gmail.com>"]

[workspace]
projects = ["test", "docs"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DistSSHBase = "f0a69307-14e5-4272-8c28-20680d05bac8"
DistSSHUp = "76a6745a-cbcc-444e-a19a-dcac12a79e7c"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[sources]
DistSSHBase = {rev = "cc4d354c02bcb0ec1d28fec59479ad8dd0e5d93b", url = "https://github.com/yamanori99/DistSSHBase.jl"}
DistSSHUp = {rev = "982025e01f88377c4068b3fde428c6dcdc9127f3", url = "https://github.com/yamanori99/DistSSHUp.jl"}

[compat]
Dates = "1.11"
DistSSHBase = "0.1"
DistSSHUp = "0.1"
Distributed = "1.11"
Pkg = "1.13"
TOML = "1"
julia = "1.13"

[apps.distsshrun]
julia_flags = ["--startup-file=no"]
