# Shared helpers for real-SSH E2E (docker-ssh workers).

if !isdefined(Main, :_ssh_e2e_enabled)

    using Dates
    using DistSSHUp

    """True when CI / local docker-ssh E2E should run."""
    function _ssh_e2e_enabled()::Bool
        return get(ENV, "DISTSSHKIT_SSH_E2E", "") == "1"
    end

    """Path to `testenv/docker-ssh` (repo-relative)."""
    function _docker_ssh_root()::String
        return abspath(joinpath(_kit_root(), "testenv", "docker-ssh"))
    end

    """SSH config / hosts file generated by `scripts/gen-keys.sh`."""
    function _docker_ssh_generated()
        root = _docker_ssh_root()
        return (
            ssh_config = joinpath(root, ".generated", "ssh_config"),
            hosts_file = joinpath(root, ".generated", "hosts"),
            controller_key = joinpath(root, ".generated", "controller"),
        )
    end

    """ENV overlay so DistSSHRun uses the docker-ssh SSH config (`-F`)."""
    function _ssh_e2e_env(;
            remote_project::AbstractString,
            extra::Dict{String, String} = Dict{String, String}(),
        )::Dict{String, String}
        g = _docker_ssh_generated()
        isfile(g.ssh_config) || error("missing $(g.ssh_config); run testenv/docker-ssh/scripts/up.sh")
        base = Dict{String, String}(
            "DISTSSHKIT_YES" => "1",
            "DISTSSHKIT_QUIET" => get(ENV, "DISTSSHKIT_QUIET", "1"),
            "DISTRIBUTED_SSH_OPTS" => "-F $(g.ssh_config) -o RequestTTY=no",
            "DISTRIBUTED_REMOTE_PROJECT_ROOT" => String(remote_project),
            # setup --sync / git push use this; DistSSHRun's git_push_project! has no -F flag.
            "GIT_SSH_COMMAND" => "ssh -F $(g.ssh_config) -o RequestTTY=no",
        )
        return merge(base, extra)
    end

    """`ssh -F docker-ssh config HOST REMOTE_CMD` (same RequestTTY policy as kit defaults).

    Setup existence checks (`test -e` / `test -d`), git, rsync, and `pgrep` stay
    here. Remote Julia work uses `_e2e_run_on_host`.
    """
    function _ssh_e2e_ssh(host::AbstractString, remote_cmd::AbstractString)
        g = _docker_ssh_generated()
        return _run_subprocess(
            Cmd(
                [
                    "ssh", "-F", g.ssh_config, "-o", "RequestTTY=no",
                    String(host), String(remote_cmd),
                ]
            )
        )
    end

    """Capture stdout of remote Julia via kit `ssh_opts` + `run_on_host` inner sh.

    Call under `withenv` that sets `DISTRIBUTED_SSH_OPTS` (E2E `_ssh_e2e_env`).
    """
    function _e2e_run_on_host(host::AbstractString, argv::AbstractVector{<:AbstractString})
        inner = DistSSHBase._run_on_host_remote_sh(String[String(a) for a in argv])
        return _run_subprocess(Cmd(vcat(["ssh"], DistSSHRun.ssh_opts(), [String(host), inner])))
    end

    """SSH Host names of the two workers (`child-1`, `child-2`)."""
    _ssh_e2e_hosts() = ("child-1", "child-2")
    """Remote project root for the main rsync suite."""
    _ssh_e2e_remote_root() = "/home/dev/distsshkit-e2e"

    """juliaup channels baked into the worker image (from `up.sh` / julia-slots.env)."""
    function _ssh_e2e_julia_channels()::NamedTuple{(:default, :alt), Tuple{String, String}}
        def = strip(get(ENV, "DISTSSHKIT_E2E_JULIA_DEFAULT_CHANNEL", ""))
        alt = strip(get(ENV, "DISTSSHKIT_E2E_JULIA_ALT_CHANNEL", ""))
        isempty(def) && (def = DistSSHRun.juliaup_channel())
        isempty(alt) && throw(
            ArgumentError(
                "DISTSSHKIT_E2E_JULIA_ALT_CHANNEL unset; run testenv/docker-ssh/scripts/up.sh --e2e " *
                    "(or apple-container-ssh) so slots min/max are exported",
            )
        )
        return (; default = String(def), alt = String(alt))
    end

    """Default channel from remote `juliaup status` (`*` row)."""
    function _ssh_e2e_juliaup_remote_default_channel(host::AbstractString)::String
        proc, out = _ssh_e2e_ssh(host, "\$HOME/.juliaup/bin/juliaup status")
        proc.exitcode == 0 || error("juliaup status on $host failed: $out")
        ch = DistSSHUp._juliaup_default_channel_from_status(out)
        ch === nothing && error("no default channel in juliaup status on $host:\n$out")
        return ch
    end

    """Set remote juliaup default channel (`\$HOME/.juliaup/bin/juliaup default …`)."""
    function _ssh_e2e_juliaup_default!(host::AbstractString, channel::AbstractString)
        ch = String(channel)
        proc, out = _ssh_e2e_ssh(
            host,
            "\$HOME/.juliaup/bin/juliaup default $(Base.shell_escape(ch))",
        )
        proc.exitcode == 0 || error("juliaup default $ch on $host failed: $out")
        DistSSHBase.clear_detect_julia_path_cache!(String(host))
        return nothing
    end

    """Local juliaup on the kit parent (required for `setup --juliaup parent` E2E)."""
    function _ssh_e2e_local_juliaup()::String
        ju = DistSSHBase.find_local_juliaup()
        ju === nothing && error(
            "local juliaup not found; kit parent E2E needs \$HOME/.juliaup/bin/juliaup " *
                "or Homebrew juliaup",
        )
        return ju
    end

    """`juliaup default` on the kit parent (`add` first if the channel is missing)."""
    function _ssh_e2e_juliaup_default_local!(channel::AbstractString)
        ju = _ssh_e2e_local_juliaup()
        ch = String(channel)
        add = run(ignorestatus(Cmd([ju, "add", ch])); wait = true)
        if add.exitcode != 0
            st = try
                read(Cmd([ju, "status"]), String)
            catch
                ""
            end
            occursin(ch, st) || error("juliaup add $ch failed on kit parent")
        end
        run(Cmd([ju, "default", ch]); wait = true)
        return nothing
    end

    """Version of the Julia shim beside the kit parent's juliaup."""
    function _ssh_e2e_local_juliaup_julia_version()::VersionNumber
        ju = _ssh_e2e_local_juliaup()
        jl = DistSSHBase._local_julia_beside_juliaup(ju)
        isfile(jl) || error("Julia not found beside juliaup: $jl")
        ver = DistSSHBase.parse_julia_version(read(`$jl --version`, String))
        ver === nothing && error("unparseable julia --version from $jl")
        return ver
    end

    """Channel string for the kit parent's current juliaup default shim."""
    function _ssh_e2e_local_juliaup_default_channel()::String
        return DistSSHRun.juliaup_channel(_ssh_e2e_local_juliaup_julia_version())
    end
    """Empty-tree `go --rsync` root. A later nonempty `--rsync` check uses another path."""
    _ssh_e2e_go_rsync_remote_root() = "/home/dev/distsshkit-e2e-go-rsync"
    """Separate tree for git clone/sync/`--require-git` (rsync excludes `.git/`)."""
    _ssh_e2e_git_remote_root() = "/home/dev/distsshkit-e2e-git"
    """Tilde layout for collect path-boundary coverage (`dev` → `/home/dev/…`)."""
    _ssh_e2e_tilde_remote_root() = "~/distsshkit-e2e-tilde"
    """Bare git origin path on child-1."""
    _ssh_e2e_bare_origin() = "/home/dev/distsshkit-e2e-origin.git"
    """Compose DNS URL of the bare origin, reachable from both children."""
    _ssh_e2e_bare_ssh_from_workers() = "dev@child-1:/home/dev/distsshkit-e2e-origin.git"

    """Root for kept SSH E2E artifacts: `test/artifacts/ssh-e2e/` (gitignored)."""
    function _ssh_e2e_artifact_root()::String
        return joinpath(_kit_root(), "test", "artifacts", "ssh-e2e")
    end

    """
    One SSH E2E invocation.

    Open `SUMMARY.txt` first. Step captures live under `logs/`.
    Temporary Julia projects used as `--project` live under `projects/`.
    """
    mutable struct SshE2ESuite
        dir::String
        logs::String
        project_local::String
        project_remote::String
        step::Int
        rows::Vector{NTuple{4, String}}  # status, nn, name, rel_log
    end

    function _ssh_e2e_write_summary!(suite::SshE2ESuite)
        path = joinpath(suite.dir, "SUMMARY.txt")
        open(path, "w") do io
            println(io, "SSH E2E SUMMARY — open this first")
            println(io)
            println(io, "  ok/FAIL   step   name                        log file")
            println(io, "  ---------------------------------------------------------------")
            if isempty(suite.rows)
                println(io, "  (no steps yet)")
            else
                for (status, nn, name, rel) in suite.rows
                    println(io, "  $(rpad(status, 4))     $(nn)     $(rpad(name, 28))  $(rel)")
                end
            end
            println(io)
            jp = joinpath(suite.dir, "JULIA_PATHS.txt")
            if isfile(jp)
                println(io, "Julia paths (see JULIA_PATHS.txt):")
                for line in eachline(jp)
                    println(io, "  ", line)
                end
                println(io)
            end
            println(io, "Log header:  === NN  name  [ok|FAIL]  exit=N ===")
            println(io, "Suite: $(suite.dir)")
        end
        write(joinpath(_ssh_e2e_artifact_root(), "LATEST"), suite.dir * "\n")
        return path
    end

    """Append one kit-parent/remote Julia resolution line for SUMMARY."""
    function _ssh_e2e_record_julia!(
            suite::SshE2ESuite,
            role::AbstractString,
            path::AbstractString,
            version::AbstractString,
        )
        open(joinpath(suite.dir, "JULIA_PATHS.txt"), "a") do io
            println(io, "$(role)\t$(path)\t$(version)")
        end
        return _ssh_e2e_write_summary!(suite)
    end

    """
    Create one artifact dir for the whole `run.jl` and call `f(suite)`.

      SUMMARY.txt
      logs/NN_name.log
      projects/local/
      projects/remote/
    """
    function _with_ssh_e2e_suite(f::Function)
        root = _ssh_e2e_artifact_root()
        mkpath(root)
        stamp = Dates.format(Dates.now(Dates.UTC), "yyyymmddTHHMMSS") * "Z"
        dir = abspath(joinpath(root, "$(stamp)_suite"))
        logs = joinpath(dir, "logs")
        project_local = joinpath(dir, "projects", "local")
        project_remote = joinpath(dir, "projects", "remote")
        mkpath(logs)
        mkpath(project_local)
        mkpath(project_remote)
        suite = SshE2ESuite(dir, logs, project_local, project_remote, 0, NTuple{4, String}[])
        _ssh_e2e_write_summary!(suite)
        @info "SSH E2E artifacts" summary = joinpath(dir, "SUMMARY.txt")
        try
            return f(suite)
        finally
            _ssh_e2e_write_summary!(suite)
            @info "SSH E2E done — open SUMMARY.txt" joinpath(suite.dir, "SUMMARY.txt")
        end
    end

    """Newest `*.log` under `dir`, or `nothing`."""
    function _ssh_e2e_newest_log(dir::AbstractString)::Union{Nothing, String}
        isdir(dir) || return nothing
        files = filter(f -> endswith(lowercase(f), ".log") && isfile(f), readdir(dir; join = true))
        isempty(files) && return nothing
        return last(sort(files; by = mtime))
    end

    """Save capture as `logs/NN_<slug>.log` and append a SUMMARY row.

    When `project` + `kit` (`:setup` / `:go`) are set, prefer the kit log:
    setup under `project/.distsshkit/setup/`, go under the latest go batch
    (`go_*.log` next to `kit.progress`).
    """
    function _ssh_e2e_record!(
            suite::SshE2ESuite,
            slug::AbstractString,
            proc,
            out::AbstractString;
            expect_ok::Bool = true,
            project::Union{Nothing, AbstractString} = nothing,
            kit::Union{Nothing, Symbol} = nothing,
        )
        suite.step += 1
        nn = lpad(suite.step, 2, '0')
        safe = replace(String(slug), r"[^A-Za-z0-9._-]+" => "_")
        rel = "logs/$(nn)_$(safe).log"
        path = joinpath(suite.dir, rel)
        ok = expect_ok ? (proc.exitcode == 0) : (proc.exitcode != 0)
        status = ok ? "ok" : "FAIL"

        body = String(out)
        kit_src = nothing
        if project !== nothing && kit !== nothing
            log_dir = if kit === :go
                batch = _ssh_e2e_latest_go_batch(project)
                batch === nothing ? nothing : batch
            else
                joinpath(project, ".distsshkit", String(kit))
            end
            newest = log_dir === nothing ? nothing : _ssh_e2e_newest_log(log_dir)
            if newest !== nothing
                kit_src = newest
                body = read(newest, String)
            end
        end

        # `let` so the `open` do-block does not box soft locals (JETLS).
        let body = body, kit_src = kit_src
            open(path, "w") do io
                println(io, "=== $(nn)  $(slug)  [$(status)]  exit=$(proc.exitcode) ===")
                kit_src !== nothing && println(io, "kit-log: $(kit_src)")
                println(io)
                print(io, body)
                endswith(body, "\n") || println(io)
            end
        end
        push!(suite.rows, (status, nn, String(slug), rel))
        _ssh_e2e_write_summary!(suite)
        return path
    end

    """Record an in-process API step (no subprocess). `ok` maps to exit 0/1."""
    function _assert_ssh_e2e_api_ok(
            suite::SshE2ESuite,
            slug::AbstractString,
            ok::Bool,
            detail::AbstractString = ""
        )
        body = isempty(detail) ? (ok ? "ok" : "FAIL") : detail
        return _assert_ssh_e2e_ok(suite, slug, (; exitcode = ok ? 0 : 1), body)
    end

    """Record + `_assert_proc_ok` (expects exit 0)."""
    function _assert_ssh_e2e_ok(
            suite::SshE2ESuite,
            slug::AbstractString,
            proc,
            out::AbstractString;
            project::Union{Nothing, AbstractString} = nothing,
            kit::Union{Nothing, Symbol} = nothing,
        )
        _ssh_e2e_record!(suite, slug, proc, out; expect_ok = true, project = project, kit = kit)
        return _assert_proc_ok(proc, out; label = slug)
    end

    """Init a minimal git repo in `proj` so setup --check can read a local hash."""
    function _git_init_commit!(proj::AbstractString; message::AbstractString = "e2e")
        run(pipeline(`git -C $proj init`; stdout = devnull, stderr = devnull))
        run(pipeline(`git -C $proj config user.email "e2e@distsshkit.test"`; stdout = devnull, stderr = devnull))
        run(pipeline(`git -C $proj config user.name "DistSSHRun E2E"`; stdout = devnull, stderr = devnull))
        run(pipeline(`git -C $proj add -A`; stdout = devnull, stderr = devnull))
        run(pipeline(`git -C $proj commit -m $message`; stdout = devnull, stderr = devnull))
        return nothing
    end

    """Copy DistSSHRun `Project.toml` + `src/` into `proj/deps/DistSSHRun` (relative path dep)."""
    function _vendor_distsshkit!(proj::AbstractString; kit_root::AbstractString = _kit_root())
        dest = joinpath(proj, "deps", "DistSSHRun")
        isdir(dest) && rm(dest; recursive = true)
        mkpath(dest)
        cp(joinpath(kit_root, "Project.toml"), joinpath(dest, "Project.toml"); force = true)
        cp(joinpath(kit_root, "src"), joinpath(dest, "src"); force = true)
        return dest
    end

    """Job `test/runtests.jl` for SshE2EApp. `fail=true` is a remote Pkg.test() miss."""
    function _ssh_e2e_job_runtests_src(; fail::Bool = false)::String
        fail && return """
        using Test
        @testset "SshE2EApp job env" begin
            @test false
        end
        """
        return """
        using Test
        using SshE2EApp
        using DistSSHRun
        @testset "SshE2EApp job env" begin
            @test SshE2EApp isa Module
            @test DistSSHRun isa Module
        end
        """
    end

    """Overwrite `test/runtests.jl` on each remote (after rsync; does not dirty local git)."""
    function _ssh_e2e_push_job_runtests!(
            hosts,
            remote_root::AbstractString;
            fail::Bool = false,
        )
        g = _docker_ssh_generated()
        src = _ssh_e2e_job_runtests_src(; fail = fail)
        mktemp() do path, io
            write(io, src)
            flush(io)
            for host in hosts
                proc, out = _run_subprocess(
                    Cmd(
                        [
                            "scp", "-F", g.ssh_config, path,
                            "$(host):$(remote_root)/test/runtests.jl",
                        ]
                    )
                )
                _assert_proc_ok(proc, out; label = "scp job runtests $(host)")
            end
        end
        return nothing
    end

    """
    Stage a durable SSH E2E remote project: vendored DistSSHRun, demos, smoke,
    `Pkg.instantiate`, and a git commit (for setup --check).
    """
    function _stage_ssh_e2e_remote_host!(
            proj::AbstractString;
            kit_root::AbstractString = _kit_root(),
            julia::AbstractString = _julia_exe(),
        )
        proj = abspath(proj)
        _vendor_distsshkit!(proj; kit_root = kit_root)
        write(
            joinpath(proj, "Project.toml"),
            """
            name = "SshE2EApp"
            uuid = "aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee"
            version = "0.0.1"

            [deps]
            DistSSHRun = "b568025c-2759-4ef1-8b14-17d00e2cd000"
            Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"

            [sources]
            DistSSHRun = {path = "deps/DistSSHRun"}

            [extras]
            Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

            [targets]
            test = ["Test"]
            """,
        )
        mkpath(joinpath(proj, "src"))
        write(joinpath(proj, "src", "SshE2EApp.jl"), "module SshE2EApp\nend\n")
        mkpath(joinpath(proj, "test"))
        write(joinpath(proj, "test", "runtests.jl"), _ssh_e2e_job_runtests_src())

        for (subdir, names) in (
                ("with_kit", ("square_echo.jl", "square_file.jl", "pipeline_square.jl")),
                ("without_kit", ("pi_echo.jl", "pi_file.jl", "pipeline_pi.jl")),
            )
            dest = joinpath(proj, "demos", subdir)
            mkpath(dest)
            for name in names
                src = joinpath(kit_root, "demos", subdir, name)
                isfile(src) || error("missing demo: $src")
                cp(src, joinpath(dest, name); force = true)
            end
        end
        cp(_fixture("drive_local_smoke.jl"), joinpath(proj, "smoke.jl"); force = true)
        cp(_fixture("drive_remote_error.jl"), joinpath(proj, "fail.jl"); force = true)
        cp(_fixture("drive_worker_file.jl"), joinpath(proj, "worker_file.jl"); force = true)
        cp(_fixture("drive_sleep.jl"), joinpath(proj, "sleep.jl"); force = true)
        cp(_fixture("ride_sleep.jl"), joinpath(proj, "ride_sleep.jl"); force = true)

        # Kit logs / demo outputs must not dirty the tree: setup --sync requires clean git.
        write(
            joinpath(proj, ".gitignore"),
            """
            .distsshkit/
            output/
            results/
            """,
        )

        inst = setenv(
            `$julia --startup-file=no --project=$proj -e "using Pkg; Pkg.instantiate()"`,
            _child_julia_env(),
        )
        proc, out = _run_subprocess(inst)
        _assert_proc_ok(proc, out; label = "ssh-e2e Pkg.instantiate")

        _git_init_commit!(proj)
        return nothing
    end

    """Newest go batch dir (`go_manifest.txt` under `.distsshkit/go/`), or `nothing`."""
    function _ssh_e2e_latest_go_batch(proj::AbstractString)::Union{Nothing, String}
        candidates = String[]
        isdir(proj) || return nothing
        for (root, dirs, _) in walkdir(proj)
            basename(root) == "go" || continue
            occursin(".distsshkit", root) || continue
            for name in dirs
                p = joinpath(root, name)
                isfile(joinpath(p, "go_manifest.txt")) && push!(candidates, p)
            end
        end
        isempty(candidates) && return nothing
        return last(sort(candidates; by = mtime))
    end

    """Kit parent → bare URL using docker-ssh Host alias (`User`/`Port` from ssh_config)."""
    function _ssh_e2e_bare_origin_from_controller()::String
        return _ssh_e2e_hosts()[1] * ":" * _ssh_e2e_bare_origin()
    end

    """
    Seed a bare origin on child-1, point local `origin` at it, push HEAD.

    Workers clone via `_ssh_e2e_bare_ssh_from_workers()` (compose DNS + inter-worker key).
    """
    function _ssh_e2e_seed_git_origin!(proj::AbstractString)
        g = _docker_ssh_generated()
        ssh_base = String["ssh", "-F", String(g.ssh_config)]
        bare = _ssh_e2e_bare_origin()
        seed_host = String(_ssh_e2e_hosts()[1])
        git_remote = _ssh_e2e_git_remote_root()

        # Fresh bare on child-1.
        proc, out = _run_subprocess(
            Cmd(
                vcat(
                    ssh_base,
                    String[seed_host, "rm -rf $(bare) $(git_remote) && git init --bare $(bare)"],
                )
            )
        )
        _assert_proc_ok(proc, out; label = "ssh-e2e git init --bare")

        # Children accept child-1 host key once (git clone uses plain ssh).
        for host in _ssh_e2e_hosts()
            proc, out = _run_subprocess(
                Cmd(
                    vcat(
                        ssh_base,
                        String[
                            String(host),
                            "ssh -o BatchMode=yes -o StrictHostKeyChecking=accept-new -o ConnectTimeout=5 " *
                                "dev@child-1 'echo ok'",
                        ],
                    )
                )
            )
            _assert_proc_ok(proc, out; label = "ssh-e2e warm child-1 hostkey from $host")
        end

        proj = abspath(proj)
        # Detach any previous origin; set kit-parent-reachable origin for push/sync.
        try
            run(pipeline(`git -C $proj remote remove origin`; stdout = devnull, stderr = devnull))
        catch
        end
        origin = _ssh_e2e_bare_origin_from_controller()
        run(`git -C $proj remote add origin $origin`)

        # Prefer main; fall back to whatever HEAD is.
        branch = try
            strip(read(`git -C $proj rev-parse --abbrev-ref HEAD`, String))
        catch
            "master"
        end
        isempty(branch) && (branch = "master")

        git_ssh = "ssh -F $(g.ssh_config) -o RequestTTY=no"
        push_cmd = setenv(
            `git -C $proj push -u origin HEAD:$(branch)`,
            Dict("GIT_SSH_COMMAND" => git_ssh),
        )
        proc, out = _run_subprocess(push_cmd)
        _assert_proc_ok(proc, out; label = "ssh-e2e git push origin")
        return (; origin_controller = origin, origin_workers = _ssh_e2e_bare_ssh_from_workers(), branch)
    end

    """`git push` HEAD to `origin` using docker-ssh `-F` (for setup --pull after a local bump)."""
    function _ssh_e2e_git_push!(proj::AbstractString)
        g = _docker_ssh_generated()
        proj = abspath(proj)
        push_cmd = setenv(
            `git -C $proj push origin HEAD`,
            Dict("GIT_SSH_COMMAND" => "ssh -F $(g.ssh_config) -o RequestTTY=no"),
        )
        proc, out = _run_subprocess(push_cmd)
        _assert_proc_ok(proc, out; label = "ssh-e2e git push")
        return nothing
    end

    """Make a sync-test commit on `proj` and leave the working tree clean."""
    function _ssh_e2e_git_bump_commit!(proj::AbstractString; message::AbstractString = "e2e-sync")
        proj = abspath(proj)
        marker = joinpath(proj, "e2e_sync_marker.txt")
        write(marker, string(time()) * "\n")
        run(pipeline(`git -C $proj add -A`; stdout = devnull, stderr = devnull))
        run(pipeline(`git -C $proj commit -m $message`; stdout = devnull, stderr = devnull))
        DistSSHRun.local_git_clean(proj) || error(
            "e2e bump left a dirty tree:\n" *
                read(pipeline(`git -C $proj status --porcelain`; stderr = devnull), String),
        )
        return DistSSHRun.get_local_git_hash(proj; short = 12)
    end

end
